const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..');const ts=require(path.join(root,'node_modules/typescript'));
const source=ts.createSourceFile('db.ts',fs.readFileSync(path.join(root,'src/server/db.ts'),'utf8'),ts.ScriptTarget.Latest,true);
const fns=source.statements.filter(n=>ts.isFunctionDeclaration(n)&&['adminResetPassword','changeUserCredentialAtomic','changeOwnPassword'].includes(n.name?.text));assert.equal(fns.length,3);
const js=ts.transpileModule(fns.map(fn=>fn.getText(source).replace(/^export /,'')).join('\n'),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
function setup(pg=false,fail=''){
 const calls=[],writes=[];let released=0,missing=false;
 const user={id:'qa',username:'qa',email:'',rol:'professional',activo:true,nombre:'QA',passwordHash:'old',salt:'old',password:'legacy',createdAt:'2026-01-01',updatedAt:'2026-01-01'};
 const row={id:'qa',username:'qa',email:'',rol:'professional',activo:true,nombre:'QA',password_hash:'old',salt:'old',created_at:'2026-01-01',updated_at:'2026-01-01'};
 const client={query:async(sql,args)=>{const q=sql.trim().replace(/\s+/g,' ');calls.push(q);if(fail&&q.startsWith(fail))throw Error('private-sql-detail');if(q.startsWith('SELECT'))return {rows:missing?[]:[row],rowCount:missing?0:1};if(q.startsWith('UPDATE users'))return {rows:[{...row,password_hash:'hash',salt:'salt',must_change_password:args[3]}],rowCount:1};return {rows:[],rowCount:1};},release:()=>released++};
 const ctx={crypto:{randomUUID:()=> 'test-id',randomBytes:()=>({toString:()=> 'random-id'})},path,fs:{openSync:()=>99,closeSync:()=>{},existsSync:()=>true,mkdirSync:()=>{},writeFileSync:(file,data)=>{if(fail==='write')throw Error('disk');writes.push({file,data});},renameSync:()=>{if(fail==='rename')throw Error('disk');},unlinkSync:()=>{}},DATA_DIR:'C:/isolated-qa',DATA_FILE:'C:/isolated-qa/db.json',process:{pid:99},isPostgresConnected:pg,pgPool:{connect:async()=>client,query:()=>{throw Error('Pool query outside transaction');}},verifyPassword:p=>p==='Existing!7',validatePasswordPolicy:p=>({valid:typeof p==='string'&&p.length>=8,error:'invalid'}),hashPassword:()=>({hash:'hash',salt:'salt'}),memoryDb:{users:[user],sessions:[{id:'a',userId:'qa',revokedAt:null},{id:'b',userId:'other',revokedAt:null}],auditLogs:[]}};
 vm.createContext(ctx);vm.runInContext(js,ctx);return {ctx,calls,writes,released:()=>released,missing:()=>{missing=true;ctx.memoryDb.users=[];}};
}
(async()=>{let count=0;
 const m=setup();const out=await m.ctx.adminResetPassword('qa','Synthetic!7','admin','QA');assert.equal(out.passwordHash,undefined);assert.equal(out.salt,undefined);assert.equal(out.password,undefined);assert.equal(m.ctx.memoryDb.users[0].mustChangePassword,true);assert.ok(m.ctx.memoryDb.sessions[0].revokedAt);assert.equal(m.ctx.memoryDb.sessions[1].revokedAt,null);assert.equal(m.ctx.memoryDb.auditLogs.length,1);assert.equal(m.writes.length,1);assert.equal(m.writes[0].data.includes('Synthetic!7'),false);count++;
 for(const fail of ['write','rename']){const t=setup(false,fail),before=JSON.stringify(t.ctx.memoryDb);await assert.rejects(()=>t.ctx.adminResetPassword('qa','Synthetic!7'));assert.equal(JSON.stringify(t.ctx.memoryDb),before);count++;}
 for(const pg of [false,true]){const t=setup(pg);t.missing();assert.equal(await t.ctx.adminResetPassword('qa','Synthetic!7'),null);assert.equal(t.writes.length,0);if(pg)assert.equal(t.released(),1);count++;}
 const p=setup(true),before=JSON.stringify(p.ctx.memoryDb);const u=await p.ctx.adminResetPassword('qa','Synthetic!7','admin','QA');assert.ok(u);assert.equal(u.passwordHash,undefined);assert.equal(u.salt,undefined);assert.equal(p.calls[0],'BEGIN');assert.ok(p.calls.some(q=>q.startsWith('SELECT')&&q.includes('FOR UPDATE')));assert.ok(p.calls.some(q=>q.startsWith('UPDATE sessions')));assert.ok(p.calls.some(q=>q.startsWith('INSERT INTO audit_logs')));assert.equal(p.calls.at(-1),'COMMIT');assert.equal(p.released(),1);assert.equal(JSON.stringify(p.ctx.memoryDb),before);count++;
 for(const fail of ['UPDATE users','UPDATE sessions','INSERT INTO audit_logs']){const t=setup(true,fail),b=JSON.stringify(t.ctx.memoryDb);await assert.rejects(()=>t.ctx.adminResetPassword('qa','Synthetic!7'),e=>!e.message.includes('private-sql-detail'));assert.ok(t.calls.includes('ROLLBACK'));assert.equal(t.calls.includes('COMMIT'),false);assert.equal(t.released(),1);assert.equal(JSON.stringify(t.ctx.memoryDb),b);count++;}
 for(const pg of [false,true]){
  const t=setup(pg);const u=await t.ctx.changeOwnPassword('qa','Existing!7','Synthetic!7');assert.equal(u.mustChangePassword,false);if(!pg)assert.equal(t.ctx.memoryDb.auditLogs[0].evento,'password_changed');count++;
  for(const oldPassword of ['wrong','']){const x=setup(pg),before=JSON.stringify(x.ctx.memoryDb);await assert.rejects(()=>x.ctx.changeOwnPassword('qa',oldPassword,'Synthetic!7'));assert.equal(JSON.stringify(x.ctx.memoryDb),before);assert.equal(x.calls.some(q=>q.startsWith('UPDATE')),false);count++;}
  const same=setup(pg);await assert.rejects(()=>same.ctx.changeOwnPassword('qa','Existing!7','Existing!7'));assert.equal(same.calls.length,0);count++;
 }
 console.log('PASS '+count+' atomic-reset control-flow cases with SQL/fs mocked; no integration DB or filesystem writes');
})().catch(e=>{console.log('FAIL '+e.name+': '+e.message);process.exitCode=1;});
