const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'); const ts=require(path.join(root,'node_modules/typescript'));
const src=ts.createSourceFile('server.ts',fs.readFileSync(path.join(root,'server.ts'),'utf8'),ts.ScriptTarget.Latest,true);
let handler; function visit(n){if(ts.isCallExpression(n)&&n.expression.getText(src)==='app.post'&&n.arguments[0]?.text==='/api/auth/password-change')handler=n.arguments[n.arguments.length-1];ts.forEachChild(n,visit);}visit(src);assert.ok(handler);
const js=ts.transpileModule('const handler='+handler.getText(src),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
async function run(body,fail=false){const calls=[];let code=200,payload;const ctx={getUserById:async()=>({passwordHash:'hash',salt:'salt',username:' QaUser1! '}),verifyPassword:p=>p==='SyntheticOld!7',validatePasswordPolicy:p=>({valid:p.length>=8,error:'Policy rejected'}),updateUser:async()=>{calls.push('update');if(fail)throw Error('Write failed');},revokeAllUserSessions:async()=>calls.push('revoke'),createAuditLog:async()=>calls.push('audit'),console:{error:()=>{}}};vm.createContext(ctx);vm.runInContext(js+';globalThis.runHandler=handler;',ctx);const res={status:n=>{code=n;return res;},json:p=>{payload=p;return res;}};await ctx.runHandler({body,user:{id:'qa',username:'qa'}},res);return {code,payload,calls};}
(async()=>{let count=0;for(const invalid of [null,{},[],42,true,'']){for(const field of ['currentPassword','newPassword']){const r=await run({currentPassword:'SyntheticOld!7',newPassword:'SyntheticNew!8',[field]:invalid});assert.equal(r.code,400);assert.equal(r.calls.length,0);count++;}}
for(const [old,next] of [['wrong','SyntheticNew!8'],['SyntheticOld!7','SyntheticOld!7'],['SyntheticOld!7','qauser1!']]){const r=await run({currentPassword:old,newPassword:next});assert.equal(r.code,400);assert.equal(r.calls.length,0);count++;}
const ok=await run({currentPassword:'SyntheticOld!7',newPassword:'SyntheticNew!8'});assert.equal(ok.code,200);assert.equal(ok.payload.success,true);assert.equal(ok.calls.join(','),'update,revoke,audit');count++;
const failed=await run({currentPassword:'SyntheticOld!7',newPassword:'SyntheticNew!8'},true);assert.equal(failed.code,400);assert.equal(failed.calls.join(','),'update');assert.notEqual(failed.payload.success,true);count++;
console.log('PASS '+count+' isolated password-change handler cases; all dependencies mocked');})().catch(e=>{console.log('FAIL '+e.name);process.exitCode=1;});
